import jsPDF from 'jspdf';

export async function exportApplicationsPDF(
  programs: any[],
  userProfile: any
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;
  let y = 20;
  
  // Header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('GradOS - Application Summary', 20, y);
  y += 8;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(
    `Generated: ${new Date().toLocaleDateString('en-GB', { 
      day: 'numeric', month: 'long', year: 'numeric' 
    })}`, 
    20, y
  );
  y += 5;
  
  if (userProfile?.full_name) {
    doc.text(`Applicant: ${userProfile.full_name}`, 20, y);
    y += 5;
  }
  
  // Divider
  doc.setDrawColor(200);
  doc.line(20, y, pageWidth - 20, y);
  y += 10;
  
  // Each program
  programs.forEach((program, index) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    
    // Program heading
    doc.setFontSize(13);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0);
    doc.text(
      `${index + 1}. ${program.school_name}`, 
      20, y
    );
    y += 6;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(60);
    doc.text(program.program_name || '', 20, y);
    y += 5;
    
    // Details
    doc.setFontSize(9);
    doc.setTextColor(80);
    const details = [
      program.degree_type && 
        `Degree: ${program.degree_type}`,
      program.country && 
        `Country: ${program.country}`,
      program.deadline && 
        `Deadline: ${new Date(program.deadline)
          .toLocaleDateString('en-GB', {
            day: 'numeric', 
            month: 'long', 
            year: 'numeric'
          })}`,
      program.status && 
        `Status: ${program.status}`,
      program.portal_url && 
        `Portal: ${program.portal_url}`,
    ].filter(Boolean);
    
    details.forEach(detail => {
      doc.text(detail as string, 25, y);
      y += 4;
    });
    
    y += 6;
    
    // Divider between programs
    if (index < programs.length - 1) {
      doc.setDrawColor(220);
      doc.line(20, y, pageWidth - 20, y);
      y += 8;
    }
  });
  
  // Footer on last page
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    'Generated by GradOS — Graduate Application OS', 
    20, 
    doc.internal.pageSize.height - 10
  );
  
  return doc.output('blob');
}
